### ISSUE TITLE
[Bug]Minecraft didn't receive any Internet but the others are able to receive.

### ISSUE THREAD

**Issue by ghost** [hax0r31337/ProtoHax-Android#5]
I Logged In on my Xbox account on the ProtoHax and on Minecraft but it didn't work.What do i missed?
HELP HELP
BTW i can't join any server using Internet or Wifi when the Proxy was enabled.

**Comment by hax0r31337** [comment]
> I Logged In on my Xbox account on the ProtoHax and on Minecraft but it didn't work.What do i missed? HELP HELP BTW i can't join any server using Internet or Wifi when the Proxy was enabled.

Some users have already reported to me that they have facing the same issue that you have described, I'm currently working on trying to locate the problem.

**Comment by ghost** [comment]
Ok but how did you make it working on your phone(in the yt vid)?
[Not Important]BTW the module i see on the code is ESP only.Where's the other?

**Comment by hax0r31337** [comment]
> Ok but how did you make it working on your phone(in the yt vid)?

it just works after i logged info my microsoft account and connect the proxy

**Comment by ghost** [comment]
> > Ok but how did you make it working on your phone(in the yt vid)?
> 
> it just works after i logged info my microsoft account and connect the proxy

Wut 
First i log in my microsoft account on app
Next on the minecraft after
Next i open the proxy with mobile data enable
Next i launch minecraft and test on flat but didn't work
Last i test it on server but i cant even join the server(lifeboat).

**Comment by hax0r31337** [comment]
> > > Ok but how did you make it working on your phone(in the yt vid)?
> > 
> > 
> > it just works after i logged info my microsoft account and connect the proxy
> 
> Wut First i log in my microsoft account on app Next on the minecraft after Next i open the proxy with mobile data enable Next i launch minecraft and test on flat but didn't work Last i test it on server but i cant even join the server(lifeboat).

i'm currently not sure where is the issue causing some users unable to join into server,
and this cheat works through operating on network layer, so it will work on multiplayer only

**Comment by ghost** [comment]
![Screenshot_2023-01-29-13-00-10-73](https://user-images.githubusercontent.com/123849671/215306228-a71770d0-8a8e-49e3-ac36-394c764b2c8e.jpg)
![Screenshot_2023-01-29-13-05-13-34_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/123849671/215306253-24084beb-e94f-4c5a-9a68-20487e75f58b.jpg)
![Screenshot_2023-01-29-13-04-02-11_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/123849671/215306259-df68b126-681e-4fbd-82a7-5dee841d23ee.jpg)

**Comment by ghost** [comment]
Or does my Minecraft too updated(not really).Should i downgrade?
Im looking at the code in a hour and i cant see what the reason why this happens.

**Comment by ghost** [comment]
Hello @hax0r31337 i think the ProtoHax is blocking the microsoft authlib cuz i can't even do everything related to microsoft including minecraft.But i can do anything,play minecraft cracked server,youtube,etc.

**Comment by hax0r31337** [comment]
Fixed in [d05a9b2](https://github.com/hax0r31337/ProtoHax/commit/d05a9b2eed84175d31a26a472c3b539a11eb7a66)

**Comment by ghost** [comment]
> Fixed in [d05a9b2](https://github.com/hax0r31337/ProtoHax/commit/d05a9b2eed84175d31a26a472c3b539a11eb7a66)



> Fixed in [d05a9b2](https://github.com/hax0r31337/ProtoHax/commit/d05a9b2eed84175d31a26a472c3b539a11eb7a66)

Can you Release it?

**Comment by ghost** [comment]
Still? My Minecraft kinda didn't receive any of the mobile data(it took so long show up that my microsoft was log in and so long to connect on server but still cant connect🤔🤔🤔).

**Comment by ghost** [comment]
ProtoHax Account Manager:
![Screenshot_2023-01-31-20-21-00-87](https://user-images.githubusercontent.com/123849671/215758938-52072fff-ab65-4708-a2a7-66734f2827c1.jpg)
Minecraft Main Menu(marketplace and skin not loading):
![Screenshot_2023-01-31-20-21-56-17_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/123849671/215759220-dc0c38d0-f7d8-41a5-b4af-2ecfd4f727c5.jpg)
Bug Connecting on Server:
![Screenshot_2023-01-31-20-22-30-69_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/123849671/215759365-15618eae-7e24-45fc-ab6c-b55cc5c4e4f9.jpg)
If on Mobile Network problem,can you fix it? My Mobile Data has have an lot of GB Left so no problem on Data Connection.

**Comment by hax0r31337** [comment]
> ProtoHax Account Manager: ![Screenshot_2023-01-31-20-21-00-87](https://user-images.githubusercontent.com/123849671/215758938-52072fff-ab65-4708-a2a7-66734f2827c1.jpg) Minecraft Main Menu(marketplace and skin not loading): ![Screenshot_2023-01-31-20-21-56-17_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/123849671/215759220-dc0c38d0-f7d8-41a5-b4af-2ecfd4f727c5.jpg) Bug Connecting on Server: ![Screenshot_2023-01-31-20-22-30-69_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/123849671/215759365-15618eae-7e24-45fc-ab6c-b55cc5c4e4f9.jpg) If on Mobile Network problem,can you fix it? My Mobile Data has have an lot of GB Left so no problem on Data Connection.

can you provide logs during connect?   
you can get logs from adb `adb logcat -s ProtoHax` or from Logs tab

**Comment by ghost** [comment]
> > ProtoHax Account Manager: ![Screenshot_2023-01-31-20-21-00-87](https://user-images.githubusercontent.com/123849671/215758938-52072fff-ab65-4708-a2a7-66734f2827c1.jpg) Minecraft Main Menu(marketplace and skin not loading): ![Screenshot_2023-01-31-20-21-56-17_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/123849671/215759220-dc0c38d0-f7d8-41a5-b4af-2ecfd4f727c5.jpg) Bug Connecting on Server: ![Screenshot_2023-01-31-20-22-30-69_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/123849671/215759365-15618eae-7e24-45fc-ab6c-b55cc5c4e4f9.jpg) If on Mobile Network problem,can you fix it? My Mobile Data has have an lot of GB Left so no problem on Data Connection.
> 
> can you provide logs during connect? you can get logs from adb `adb logcat -s ProtoHax` or from Logs tab

?
![Screenshot_2023-01-31-20-32-30-58](https://user-images.githubusercontent.com/123849671/215760806-b2856665-3f62-4e42-95ff-c53ad935d305.jpg)

**Comment by ghost** [comment]
I try to connects in mineplex,cubecraft but nothing

**Comment by hax0r31337** [comment]
oops seems the logs tab buggy on your phone

**Comment by ghost** [comment]
> oops seems the logs tab buggy on your phone

Phone Specs:
Oppo A12 
RAM: 3GB
Storage: 32GB
CPU: Helio P35(MediaTek)
CPU Clusters: 4 x 2.30GHz
                   4 x 1.80GHz
GPU: PowerVR Rogue GE8320(Imagination Technologies)
OpenGL Version: 3.2
Vulcan: None
System: ColorOS 6.1(Android 9 Pie)
Screen Refresh Rate: 60.0Hz
Architecture: ARM64(64Bit)
My 5 year old phone😁😁😁

**Comment by ghost** [comment]
ProtoHax working only in specified DNS or IP address (Or on network provider).
